name: Laravel

on:
  push:
    branches: ["backend"]
  pull_request:
    branches: ["backend"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "20"

      # - name: Install dependencies
      #   run: npm install

      # - name: Build assets
      #   run: npm run build

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer update

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache deploy.sh

      - name: Directory Permissions
        run: chmod 777 deploy.sh

      - name: Clear Config
        run: php artisan config:clear

      - name: autoload
        run: composer dump-autoload

      - name: Clear route
        run: php artisan route:clear

      - name: Clear Cache
        run: php artisan cache:clear

      - name: Shut Down serve
        run: php artisan down

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: "65002"
          key: ${{ secrets.SSH_KEY }}
          script: "cd /home/u624754796/domains/acce-abuja.com/public_html/dashboard && ./deploy.sh"
